### ISSUE TITLE
A little problem about Matlab

### ISSUE THREAD

**Issue by lincoln2010** [maleadt/tracetransform#1]
When I run the demo.m in pure matlab implementation (Matlab R2015a on Windows8.1), it prompts:
 demo
Undefined function or variable 'directory'.

Error in demo (line 3)
cd(directory);
 I don't know what causes it, thank you very much if you can take a  look at it.

**Comment by maleadt** [comment]
In order to have some unified interface to call the individual ports from the command line, I've created a wrapper Perl script which in turn defines those variables, based on command line flags. So either you invoke that Perl script, or you just extend the MATLAB script to define those variables instead (just have a look at the Perl source, it's pretty self-explanatory).
